bind-key -n C-k new-window;
bind-key j kill-window;
bind-key -n C-h previous-window;
bind-key -n C-l next-window;
bind-key -n C-r command-prompt -I "#W" "rename-window '%%'";
bind-key -n C-w choose-window;

set -gq allow-passthrough on;
set -g visual-activity off;
set-option -g focus-events on;

