bind-key -n C-k new-window
bind-key -n C-j kill-window
bind-key -n C-h previous-window
bind-key -n C-l next-window
bind-key -n C-r command-prompt -I "#W" "rename-window '%%'"
bind-key -n C-w choose-window

set -s set-clipboard on
