bind-key -n C-n new-window
bind-key -n C-d confirm-before -p "Kill window #W (y/n)?" kill-window
bind-key -n C-u previous-window
bind-key -n C-p next-window
bind-key -n C-r command-prompt -I "#W" "rename-window '%%'"
bind-key -n C-w choose-window
bind-key -n C-_ split-window -v
bind-key -n C-| split-window -h
bind-key -n C-h select-pane -L
bind-key -n C-l select-pane -R
bind-key -n C-k select-pane -U
bind-key -n C-j select-pane -D

set -s set-clipboard on
set -g mouse on
set-window-option -g mode-keys vi
